# Generated by Django 3.0.7 on 2020-08-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('min_precipitation', models.FloatField()),
                ('maximim_precipitation', models.FloatField()),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('growth_habit', models.CharField(blank=True, max_length=20, null=True)),
                ('min_tempearature', models.FloatField()),
                ('shade_tolerance', models.CharField(max_length=20)),
                ('drought_tolerance', models.CharField(max_length=20)),
                ('prediction', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
