# Generated by Django 3.1 on 2020-10-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201005_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaultusers.png', upload_to='profile'),
        ),
    ]
