# Generated by Django 3.1 on 2020-12-31 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201231_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 4 to 20 characters.Beginning with an alphabet. Letters, digits and @/./+/-/_ only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid username. Must be 4 to 20 characters long, starting with an alphabet.                     Letters, digits and @/./+/-/_ only.', regex='^[a-zA-Z][\\w@+-.]{3,19}\\Z')], verbose_name='Username'),
        ),
    ]
