# Generated by Django 3.1 on 2020-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20200814_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ph', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('min_precipitation', models.FloatField()),
                ('max_precipitation', models.FloatField()),
                ('duration', models.CharField(blank=True, choices=[('perennial', 'Perennial'), ('annual', 'Annual'), ('biennial', 'Biennial')], default='annual', max_length=20, null=True)),
                ('growth_habit', models.CharField(blank=True, choices=[('shrub', 'Shrub'), ('forb/herb', 'Forb/Herb'), ('graminoid', 'Graminoid'), ('subshrub', 'Subshrub'), ('tree', 'Tree'), ('vine', 'Vine')], default='forb/herb', max_length=20, null=True)),
                ('soil_texture', models.CharField(choices=[('coarse', 'Coarse'), ('mild', 'Mild'), ('fine', 'Fine')], default='coarse', max_length=10)),
                ('min_temperature', models.FloatField()),
                ('shade_tolerance', models.CharField(choices=[('intolerant', 'Intolerant'), ('intermediate', 'Intermediate'), ('tolerant', 'Tolerant')], default='Intermediate', max_length=20)),
                ('drought_tolerance', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low', max_length=20)),
                ('prediction', models.CharField(blank=True, editable=False, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Plant_Recommend',
        ),
    ]
