# Generated by Django 3.1 on 2020-11-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20201021_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='max_ph',
            new_name='ph',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='min_ph',
        ),
    ]
