# Generated by Django 3.1 on 2020-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20201121_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='soil_texture',
            field=models.CharField(choices=[('coarse', 'Coarse'), ('medium', 'Medium'), ('fine', 'Fine')], default='coarse', max_length=10),
        ),
    ]
