# Generated by Django 3.1 on 2020-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20201121_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('scientific_name', models.CharField(max_length=25)),
                ('common_name', models.CharField(max_length=25)),
                ('duration', models.CharField(max_length=100)),
                ('growth_habit', models.CharField(max_length=100)),
            ],
        ),
    ]
