# Generated by Django 3.1 on 2020-10-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200820_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='userId',
        ),
    ]
