# Generated by Django 3.1 on 2020-10-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20201021_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='answerId',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='userId',
            new_name='user',
        ),
    ]
