# Generated by Django 3.1 on 2020-10-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_answerupvote_commentupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
