# Generated by Django 3.1 on 2020-11-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20201121_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('answered_at',)},
        ),
    ]
